<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-07-31 16:16
$extensionClassesPath = $extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('th_rating') . 'Classes/';
return array(
	'tx_thrating_controller_votecontroller' => $extensionClassesPath . 'Controller/VoteController.php',
	'tx_thrating_domain_model_rating' => $extensionClassesPath . 'Domain/Model/Rating.php',
	'tx_thrating_domain_model_ratingobject' => $extensionClassesPath . 'Domain/Model/Ratingobject.php',
	'tx_thrating_domain_model_stepconf' => $extensionClassesPath . 'Domain/Model/Stepconf.php',
	'tx_thrating_domain_model_stepname' => $extensionClassesPath . 'Domain/Model/Stepname.php',
	'tx_thrating_domain_model_syslang' => $extensionClassesPath . 'Domain/Model/Syslang.php',
	'tx_thrating_domain_model_vote' => $extensionClassesPath . 'Domain/Model/Vote.php',
	'tx_thrating_domain_model_voter' => $extensionClassesPath . 'Domain/Model/Voter.php',
	'tx_thrating_domain_repository_ratingobjectrepository' => $extensionClassesPath . 'Domain/Repository/RatingobjectRepository.php',
	'tx_thrating_domain_repository_ratingrepository' => $extensionClassesPath . 'Domain/Repository/RatingRepository.php',
	'tx_thrating_domain_repository_stepconfrepository' => $extensionClassesPath . 'Domain/Repository/StepconfRepository.php',
	'tx_thrating_domain_repository_stepnamerepository' => $extensionClassesPath . 'Domain/Repository/StepnameRepository.php',
	'tx_thrating_domain_repository_syslangrepository' => $extensionClassesPath . 'Domain/Repository/SyslangRepository.php',
	'tx_thrating_domain_repository_voterepository' => $extensionClassesPath . 'Domain/Repository/VoteRepository.php',
	'tx_thrating_domain_repository_voterrepository' => $extensionClassesPath . 'Domain/Repository/VoterRepository.php',
	'tx_thrating_domain_validator_ratingobjectvalidator' => $extensionClassesPath . 'Domain/Validator/RatingobjectValidator.php',
	'tx_thrating_domain_validator_ratingvalidator' => $extensionClassesPath . 'Domain/Validator/RatingValidator.php',
	'tx_thrating_domain_validator_stepconfvalidator' => $extensionClassesPath . 'Domain/Validator/StepconfValidator.php',
	'tx_thrating_domain_validator_stepnamevalidator' => $extensionClassesPath . 'Domain/Validator/StepnameValidator.php',
	'tx_thrating_domain_validator_votevalidator' => $extensionClassesPath . 'Domain/Validator/VoteValidator.php',
	'tx_thrating_service_accessexception' => $extensionClassesPath . 'Service/AccessException.php',
	'tx_thrating_service_cookieservice' => $extensionClassesPath . 'Service/CookieService.php',
	'tx_thrating_service_objectfactoryservice' => $extensionClassesPath . 'Service/ObjectFactoryService.php',
	'tx_thrating_utility_tcalabeluserfuncservice' => $extensionClassesPath . 'Service/TCALabelUserFuncService.php',
	'tx_thrating_viewhelpers_ratingviewhelper' => $extensionClassesPath . 'ViewHelpers/RatingViewHelper.php',
	'tx_thrating_viewhelpers_selectviewhelper' => $extensionClassesPath . 'ViewHelpers/SelectViewHelper.php',
);
?>