<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-07-31 16:16

$extensionClassesPath = t3lib_extMgm::extPath('th_rating') . 'Classes/';
return array(
	'tx_thrating_viewhelpers_abstractbackendviewhelper' => $extensionClassesPath . 'ViewHelpers/AbstractBackendViewHelper.php',
	
);
?>