# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage
          
      - name: Show GITHUB_WORKSPACE
        run: echo "GITHUB_WORKSPACE ${GITHUB_WORKSPACE}"
      
      - name: Checkout Code
        if: success()
        uses: actions/checkout@v2
        with:
          path: source

      - name: Show files
        run: find ${GITHUB_WORKSPACE} -type f -exec ls -al {} \;

      - name: Create Doxygen target directory
        run: mkdir -p ${GITHUB_WORKSPACE}/target

      - name: Generate Doxygen
        if: success()
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: /github/workspace/target
          doxyfile-path: /github/workspace/source/Build/.doxygen

      - name: Show files
        run: find ${GITHUB_WORKSPACE} -type f -exec ls -al {} \;

      - name: Deploy Doxygen
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/html
          destination_dir: new_actions
          keep_files: true
          commit_message: Update Doxygen for new release
