# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Show GITHUB_WORKSPACE
      run: echo "GITHUB_WORKSPACE ${GITHUB_WORKSPACE}"
      
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        path: source

    - name: Show files
      run: find ${GITHUB_WORKSPACE} -type d -exec ls -al {} \;
      
    - name: Create Doxygen target directory
      run: mkdir -p ${GITHUB_WORKSPACE}/target
      
    - name: Generate Doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: target
        doxyfile-path: source/Build/.doxygen

    - name: Show files
      run: find ${GITHUB_WORKSPACE} -type d -exec ls -al {} \;
      
      
      
